language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install
script:
  - psc-package install
  - npm run -s build
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp --psc-package login &&
  echo y | pulp --psc-package publish --no-push